# Generated by Django 3.1.7 on 2021-10-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_name', models.CharField(max_length=40, verbose_name='Product Name')),
                ('product_id', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Product ID')),
                ('product_size', models.CharField(default='standard', max_length=40, verbose_name='Product Size')),
                ('product_quantity', models.PositiveSmallIntegerField(verbose_name='Product Quantity')),
                ('product_price', models.FloatField(verbose_name='Product Price')),
                ('product_color', models.CharField(max_length=40, verbose_name='Product Color')),
            ],
        ),
    ]
