# Generated by Django 3.1.7 on 2021-10-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=40, verbose_name='Client Name')),
                ('client_id', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Client ID')),
                ('client_phone_number', models.CharField(max_length=40, verbose_name='Cclient Phone Number')),
                ('client_email', models.CharField(default='', max_length=40, verbose_name='Cclient Email')),
                ('client_address', models.CharField(max_length=40, verbose_name='Client Address')),
            ],
        ),
    ]
