# Generated by Django 3.1.7 on 2021-10-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211007_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('distribution_id', models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='Distribution ID')),
                ('distribution_company_name', models.CharField(max_length=40, verbose_name='Distribution Company Name')),
                ('distribution_fee', models.FloatField(verbose_name='Distribution Fee ')),
                ('distribution_order_id', models.CharField(default='', max_length=40, verbose_name='Order ID')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
    ]
