# Generated by Django 2.1.15 on 2021-10-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211009_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '入驻品牌表', 'verbose_name_plural': '入驻品牌表'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '客户单', 'verbose_name_plural': '客户单'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': '物流表', 'verbose_name_plural': '物流表'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': '评价表', 'verbose_name_plural': '评价表'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单表', 'verbose_name_plural': '订单表'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_grade',
            field=models.CharField(default='', max_length=40, verbose_name='品牌等级'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='品牌号'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='', max_length=40, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_company_name',
            field=models.CharField(max_length=40, verbose_name='物流公司名称'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_fee',
            field=models.FloatField(verbose_name='邮费'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_id',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='物流号'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_description',
            field=models.CharField(default='', max_length=40, verbose_name='评价文案'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_id',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False, verbose_name='评价号'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_order_id',
            field=models.CharField(default='', max_length=40, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_size',
            field=models.CharField(choices=[('均码', '均码'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='均码', max_length=40, verbose_name='产品尺码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_aggregate_amount',
            field=models.FloatField(verbose_name='消费总金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_purchase_quantity',
            field=models.PositiveIntegerField(verbose_name='购买数量'),
        ),
    ]
